### ISSUE TITLE
Pubsub/eventsub support

### ISSUE THREAD

**Issue by ohmree** [jkbz64/TwitchQt#5]
Do pubsub and/or eventsub fall under the scope of this?

If so I might be able to hack on this (no promises though, I'll have to learn a lot).

**Comment by jkbz64** [comment]
I don't think it is the part of the API per se but it seems to use the same authorization method and probably people who use the api would be interested in it too.

If you use/care about the library and want to improve it then sure, I dont' mind, throw the PR whenever you want 👍 
If you want to maintain the pubsub api then I can add you as the maintainer or feel free to fork/create your own project (I can maybe link to your project in the README)
